/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.poisonedyouth

import org.gradle.api.DefaultTask
import org.gradle.api.Plugin
import org.gradle.api.Project
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.TaskAction
import java.nio.file.Files

private val defaultFileTypes: List<String> = listOf("kt")
private val defaultReportFilePath: String = "build/reports/countLines.txt"

class GradleCustomPlugin : Plugin<Project> {
    override fun apply(project: Project) {
        // Register a task
        project.tasks.create("countLines", CountLinesTask::class.java)
    }
}

open class CountLinesTask : DefaultTask() {

    @Input
    var fileTypes: List<String> = defaultFileTypes

    @Input
    var reportFilePath: String = defaultReportFilePath

    @TaskAction
    fun countLines() {
        println("Start producing count lines report...")
        val result = mutableMapOf<String, Int>()
        val projectRootDir = project.rootDir
        println("Root directory: $projectRootDir")
        projectRootDir.walk()
            .filter { it.isFile && it.extension in fileTypes }
            .forEach {
                val lineCount = Files.readAllLines(it.toPath()).count()
                val existingCount = result[it.extension]
                if (existingCount == null) {
                    result[it.extension] = lineCount
                } else {
                    result.replace(it.extension, existingCount + lineCount)
                }

            }
        val reportFile = projectRootDir.toPath().resolve(reportFilePath)
        Files.createDirectories(reportFile.parent)
        Files.write(reportFile, printReport(result))
        println("Finished producing count lines report in path: $reportFilePath")
    }

    private fun printReport(result: MutableMap<String, Int>): List<String> {
        return result.map { "Filetype:${it.key} \t-\t Lines:${it.value}" }
    }
}
