/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.poisonedyouth

import org.gradle.testfixtures.ProjectBuilder
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull

/**
 * A simple unit test for the 'com.poisonedyouth.greeting' plugin.
 */
class GradleCustomPluginTest {
    @Test
    fun `plugin registers tasks`() {
        // given
        val project = ProjectBuilder.builder().build()

        // when
        project.plugins.apply("com.poisonedyouth.countLines")

        // then
        assertNotNull(project.tasks.findByName("printReportToTerminal"))
        assertNotNull(project.tasks.findByName("printReportToFile"))
    }

    @Test
    fun `plugin correctly sets defaults for printReportToFile`() {
        // given
        val project = ProjectBuilder.builder().build()

        // when
        project.plugins.apply("com.poisonedyouth.countLines")

        // then
        val task = project.tasks.getByName("printReportToFile") as PrintReportToFileTask
        assertEquals(task.fileTypes, listOf("kt"))
        assertEquals(task.reportFilePath, "build/reports/countLines.txt")
    }

    @Test
    fun `plugin correctly sets defaults for printReportToTerminal`() {
        // given
        val project = ProjectBuilder.builder().build()

        // when
        project.plugins.apply("com.poisonedyouth.countLines")

        // then
        val task = project.tasks.getByName("printReportToTerminal") as PrintReportToTerminalTask
        assertEquals(task.fileTypes, listOf("kt"))
    }
}
